### ISSUE TITLE
Implementation of graph library

### ISSUE THREAD

**Issue by dakridas** [dakridas/VerilogAPI#34]
A test implementation of the graph has began. The idea is to create, as a start, all the nodes of a module. The nodes may be input, output and internal. The input and output nodes are created from the input and output ports of the module. The next step is to create the internal nodes, from the instances's ports inside the module. 

See [graph](https://github.com/dakridas/VerilogAPI/tree/graph) branch

**Comment by paraschas** [comment]
Implemented.
