### ISSUE TITLE
Add Net Names on the graph

### ISSUE THREAD

**Issue by digaryfa** [dakridas/VerilogAPI#79]
Add the name of the corresponding Net on every NetEdge (forward and backward) of the graph

**Comment by digaryfa** [comment]
Not yet closed 
There are no Net Names on edges corresponding to **Internal Bus Wires**. 

![screenshot from 2017-09-27 14-21-42](https://user-images.githubusercontent.com/9335784/30915840-de6049f6-a38f-11e7-8805-f21fa8622bae.png)


Run: ./tester -d -v -g -n -l tests/lib/ -w tests/assign_test/ -t pfpu_rnd_marocchino

**Comment by dakridas** [comment]
No bug found. All net names are in the dot file. For some reason the xdot can't draw them.
